version: "3.7"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "$PWD/prometheus/etc/prometheus:/etc/prometheus"
      - "$PWD/prometheus/data:/prometheus"

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - "$PWD/alertmanager/etc/alertmanager:/etc/alertmanager"
      - "$PWD/alertmanager/data:/alertmanager"

  grafana:
    image: grafana/grafana
    ports:
      - "9030:3000"
    volumes:
      - "$PWD/grafana/data:/var/lib/grafana"
